---
# tasks file for ansible-zabbix-server

- name: install the zabbix repository
  yum: name={{ zabbix_repo }} state=present
  become: yes

- name: install zabbix-server-mysql
  yum: name=zabbix-server-mysql state=present
  become: yes

- name: install mariadb and mariadb-server
  yum: name={{ item }}
  with_items:
    - mariadb
    - mariadb-server
  become: yes

- name: start and enable mariadb
  service: name=mariadb state=started enabled=yes
  become: yes

- name: install zabbix-get
  yum: name=zabbix-get state=present
  become: yes

- name: check if zabbix database already exists
  shell: mysql -uroot -e "show databases" | grep zabbix
  become: yes
  register: check_database
  ignore_errors: yes
  changed_when: no

- name: create zabbix database and user
  shell: mysql -uroot -e "create database zabbix character set utf8 collate utf8_bin"
  become: yes
  when: check_database.rc != 0

- name: check if privileges need to be granted
  shell: mysql -uroot mysql -e "select * from db where host='localhost' and db='zabbix' and user='zabbix'" | grep zabbix
  become: yes
  register: check_privileges
  ignore_errors: yes
  changed_when: no

- name: grant zabbix database user privileges
  shell: mysql -uroot -e "grant all privileges on zabbix.* to zabbix@localhost identified by '{{ zabbix_db_password }}'"
  become: yes
  when: check_privileges.rc != 0

- name: check if schema and data need to be loaded
  shell: mysql -uroot zabbix -e "show tables" | grep maintenances
  become: yes
  register: check_schema
  ignore_errors: yes
  changed_when: no

- name: load zabbix schema and data
  shell: zcat create.sql.gz | mysql -uroot zabbix chdir=/usr/share/doc/zabbix-server-mysql-3.0.0
  become: yes
  when: check_schema.rc != 0

- name: configure password in zabbix_server.conf
  replace: dest=/etc/zabbix/zabbix_server.conf regexp='^# DBPassword=$' replace="DBPassword={{ zabbix_db_password }}" backup=yes
  become: yes

- name: start and enable zabbix-server
  service: name=zabbix-server state=started enabled=yes
  become: yes
