---
# tasks file for ansible-zabbix-server

- name: install the zabbix repository
  yum: name={{ zabbix.repo }} state=present
  become: yes

- name: install zabbix-server-mysql
  yum: name=zabbix-server-mysql state=present
  become: yes

- name: install mariadb and mariadb-server
  yum: name={{ item }}
  with_items:
    - mariadb
    - mariadb-server
  become: yes

- name: start and enable mariadb
  service: name=mariadb state=started enabled=yes
  become: yes

- name: install zabbix-get
  yum: name=zabbix-get state=present
  become: yes

- name: install MySQL-python
  yum:
    name: MySQL-python
    state: present

- name: create zabbix database
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    state: present

- name: create zabbix database user
  mysql_user:
    name: zabbix
    password: "{{ zabbix.database.password }}"
    priv: zabbix.*:ALL
    state: present

- name: import zabbix database schema
  mysql_db:
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql-{{ zabbix.version }}/create.sql.gz
    state: import
  ignore_errors: yes # not really nicely idempotent (bombs with 'broken pipe' if already imported)

- name: configure password in zabbix_server.conf
  replace: dest=/etc/zabbix/zabbix_server.conf regexp='^# DBPassword=$' replace="DBPassword={{ zabbix.database.password }}" backup=yes
  become: yes

- name: start and enable zabbix-server
  service: name=zabbix-server state=started enabled=yes
  become: yes
